### ISSUE TITLE
Couple of UI Inconsistencies

### ISSUE THREAD

**Issue by Queuecumber** [chaoleili/jupyterlab_tensorboard#13]
I am really loving this extension but I think it has a couple of UI inconsistencies, if these could be ironed out it would be perfect

1. Using the File -> New menu doesn't have an option to create a new tensorboard, it should really be there for consistency 
2. There is already a side panel for "running terminals and kernels" that the tensorboards should be listen in instead of making a new tab for them, that would keep all the running "things" in one place and make the side bar appear cleaner

I started preparing a pull request for this but I found the extension API to be quite poorly documented and confusing. I'm still happy to work on it but I was hoping to get some points on where to look to make the changes

**Comment by chaoleili** [comment]
Nice proposal, Thanks! But unfortunate, `using the file` and `running terminals and kernels` can't extend by other extensions, at least not work before jupyterlab v1.0.0 (i don't read any code or API after jupyterlab release the v1.0.0 version). If you want to do this, reading [running-extension](https://github.com/jupyterlab/jupyterlab/tree/master/packages/running-extension) and [filebrowser-extension](https://github.com/jupyterlab/jupyterlab/tree/master/packages/filebrowser-extension) in jupyterlab will be helpful.

**Comment by Queuecumber** [comment]
Great suggestions, I also came across this (https://github.com/jtpio/jupyterlab-python-file) today which also look instructive for number 1.

**Comment by Queuecumber** [comment]
Using that as a template I was able to make part 1 work, I'm going to submit them as separate pull requests since they are separate features

**Comment by Queuecumber** [comment]
Part 2 is currently blocked on https://github.com/jupyterlab/jupyterlab/pull/6002 which provides an API to the running panel. If the owner of that PR doesn't respond soon (by this afternoon my time) I'm going to take over that PR and get it merged, then work on integrating your extension with it

**Comment by Queuecumber** [comment]
Update on this, my patch at https://github.com/jupyterlab/jupyterlab/pull/6895 was merged which provides an API for the running tab, but because it is backwards incompatible it is being held until jupyterlab 2.0 releases. When that happens I'll submit a pr here to add the functionality

**Comment by simonrouse9461** [comment]
Jupyterlab 2.1 is out already. Any update on this?

**Comment by Queuecumber** [comment]
Thanks for the reminder, I completely forgot about this. I can probably find time to take a look at it

**Comment by simonrouse9461** [comment]
@Queuecumber Could you give it a try? I'll really appreciate that!

**Comment by Queuecumber** [comment]
Working on it now
