### ISSUE TITLE
Tensorboard 2.0 error

### ISSUE THREAD

**Issue by juliusvonkohout** [chaoleili/jupyterlab_tensorboard#16]
Hello,

There is an incompatibility with tensorboard 2.0 which was just relased with tensorflow 2.0

Event Multiplexer initializing.
Event Multiplexer done initializing
Launching reload in a daemon thread
TensorBoard reload process beginning
Starting AddRunsFromDirectory: /opt/app-root/src/logs/fit
GetLogdirSubdirectories: Starting to list directories via walking.
Adding run from directory /opt/app-root/src/logs/fit/20191001-153636/validation
Constructing EventAccumulator for /opt/app-root/src/logs/fit/20191001-153636/validation
[E 15:48:17.963 LabApp] Uncaught exception POST /api/tensorboard?1569944897920 (127.0.0.1)
HTTPServerRequest(protocol='http', host='hostname', method='POST', uri='/api/tensorboard?1569944897920', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
return method(self, *args, **kwargs)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
.new_instance(data["logdir"], reload_interval=reload_interval)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 148, in new_instance
purge_orphaned_data=purge_orphaned_data)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 46, in create_tb_app
tensorboard.assets_zip_provider)
File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 113, in TensorBoardWSGIApp
path_to_run = application.parse_event_files_spec(logdir)
File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 455, in parse_event_files_spec
for specification in logdir_spec.split(','):
AttributeError: 'Namespace' object has no attribute 'split'
Adding run from directory /opt/app-root/src/logs/fit/20191001-153636/train
Constructing EventAccumulator for /opt/app-root/src/logs/fit/20191001-153636/train
...
[E 15:48:17.968 LabApp] 500 POST /api/tensorboard?1569944897920 (127.0.0.1) 19.22ms referer=https://hostname/lab?
POST /api/tensorboard?1569944897920 500 20.322 ms - 1529
Done with AddRunsFromDirectory: /opt/app-root/src/logs/fit

**Comment by jaekookang** [comment]
Hi. I have the same issue too. Uninstalling and re-installing didn't fix the problem.

**Comment by metya** [comment]
Hi, in my case the same problem. Tensorboard just doesn't work.

**Comment by chaoleili** [comment]
lspvic/jupyter_tensorboard#55
lspvic/jupyter_tensorboard/pull/56

**Comment by metya** [comment]
Yes, but unfortunately repo of jupyter_tensorboard not much activity of this time((

**Comment by edoardogiacomello** [comment]
> [lspvic/jupyter_tensorboard#55](https://github.com/lspvic/jupyter_tensorboard/issues/55)
> [lspvic/jupyter_tensorboard/pull/56](https://github.com/lspvic/jupyter_tensorboard/pull/56)

As some users pointed out, the new official method of running tensorboard inside a notebook doesn't work if behind a firewall. Moreover the UI of this extension was more simple, since didn't require to manually type in logdirs for each tensorboard instance you wanted to run.
Is there any chance we well see an update of this? :)
