### ISSUE TITLE
having problems running through jupyterhub

### ISSUE THREAD

**Issue by joequant** [chaoleili/jupyterlab_tensorboard#8]
I'm trying to run jupyterlab_tensorboard but I'm getting a 404 error when I try to create a board.  I'm running the system behind a reverse proxy and a jupyterhub so that there may be some broken url mangling issues.

**Comment by joequant** [comment]
The api which the system creates is 

http://big-apple.local/jupyterhub/user/user/api/tensorboard?1549244001578

**Comment by chaoleili** [comment]
please install [jupyter_tensorboard](https://github.com/lspvic/jupyter_tensorboard) first, and issue #5 may be helpful.
